### ISSUE TITLE
Questions about how to train the entire network

### ISSUE THREAD

**Issue by genius9527** [LiMeng95/MultiPoseNet.pytorch#8]
Hello, see that your training is training the subnet. If you train the whole network, set subnet_name to other values, corresponding to the case of else?
        if subnet_name == 'keypoint_subnet':
            return self.keypoint_forward(img_batch)
        elif subnet_name == 'detection_subnet':
            return self.detection_forward(img_batch)
        elif subnet_name == 'prn_subnet':
            return self.prn_forward(img_batch)
        else:  # entire_net
            features = self.fpn(img_batch)
            p2, p3, p4, p5 = features[0]  # fpn features for keypoint subnet
            features = features[1]  # fpn features for keypoint subnet
Another problem is that I only saw the keypoints subnet and the detection subnet in the else. I didn't see the prn_subnet. Is there any problem here?

**Comment by LiMeng95** [comment]
@genius9527 hi,

We can not train the whole network in the same time temporarily. The '[else](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/network/posenet.py#L230)' is only useful for inference process currently.

According to section 3.5 in the [paper](https://arxiv.org/abs/1807.04067), we trained keypoint subnet, detection subnet and prn subnet separately. You can run 'multipose_keypoint_train.py, multipose_detection_train.py, multipose_prn_train.py' in order to get the final model. See [#training](https://github.com/LiMeng95/MultiPoseNet.pytorch#training).

As for prn_subnet, it's inference process is in ['prn_process' function](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/98eb0a7a37fcc50d7f2c4115da917b04895e6256/evaluate/tester.py#L317). We use this funtion on [line 159](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/98eb0a7a37fcc50d7f2c4115da917b04895e6256/evaluate/tester.py#L159) and [line 225](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L225) in 'tester.py'

**Comment by genius9527** [comment]
Thank you very much for your answer.If I want to use multipose_coco_eval.py to evaluate the performance of the entire network, which model should be loaded. Is it the last model trained by multipose_prn_train.py?

**Comment by genius9527** [comment]
> @genius9527 hi,
> 
> We can not train the whole network in the same time temporarily. The '[else](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/network/posenet.py#L230)' is only useful for inference process currently.
> 
> According to section 3.5 in the [paper](https://arxiv.org/abs/1807.04067), we trained keypoint subnet, detection subnet and prn subnet separately. You can run 'multipose_keypoint_train.py, multipose_detection_train.py, multipose_prn_train.py' in order to get the final model. See [#training](https://github.com/LiMeng95/MultiPoseNet.pytorch#training).
> 
> As for prn_subnet, it's inference process is in ['prn_process' function](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/98eb0a7a37fcc50d7f2c4115da917b04895e6256/evaluate/tester.py#L317). We use this funtion on [line 159](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/98eb0a7a37fcc50d7f2c4115da917b04895e6256/evaluate/tester.py#L159) and [line 225](https://github.com/LiMeng95/MultiPoseNet.pytorch/blob/master/evaluate/tester.py#L225) in 'tester.py'
Thank you very much for your answer.If I want to use multipose_coco_eval.py to evaluate the performance of the entire network, which model should be loaded. Is it the last model trained by multipose_prn_train.py?
